export const DEFAULT_CONFIG = {
  version: 2,
  context_strategy: 'aggressive',
  mode: 'autonomous',
  depth: 'standard',
  features: {
    structured_planning: true,
    goal_verification: true,
    integration_verification: true,
    context_isolation: true,
    atomic_commits: true,
    session_persistence: true,
    research_phase: true,
    plan_checking: true,
    tdd_mode: true,
    status_line: true,
    auto_continue: true,
    auto_advance: false,
    team_discussions: false,
    inline_verify: false,
  },
  models: {
    researcher: 'sonnet',
    planner: 'opus',
    executor: 'opus',
    verifier: 'sonnet',
    integration_checker: 'sonnet',
    debugger: 'inherit',
    mapper: 'sonnet',
    synthesizer: 'sonnet',
  },
  parallelization: {
    enabled: true,
    plan_level: true,
    task_level: false,
    max_concurrent_agents: 3,
    min_plans_for_parallel: 2,
    use_teams: false,
  },
  planning: {
    commit_docs: false,
    max_tasks_per_plan: 3,
    search_gitignored: false,
  },
  git: {
    branching: 'phase',
    commit_format: '{type}({phase}-{plan}): {description}',
    phase_branch_template: 'plan-build-run/phase-{phase}-{slug}',
    milestone_branch_template: 'plan-build-run/{milestone}-{slug}',
    mode: 'enabled',
  },
  gates: {
    confirm_project: true,
    confirm_roadmap: true,
    confirm_plan: true,
    confirm_execute: false,
    confirm_transition: true,
    issues_review: true,
    verification: true,
    review: true,
    plan_approval: true,
  },
  safety: {
    always_confirm_destructive: true,
    always_confirm_external_services: true,
  },
};

const MODEL_OPTIONS = ['opus', 'sonnet', 'haiku', 'inherit'];

export const CONFIG_SECTIONS = [
  {
    key: '_root',
    title: 'General',
    sub: 'Top-level settings',
    fields: [
      { key: 'version', label: 'Version', type: 'number', min: 1, max: 99, step: 1 },
      { key: 'context_strategy', label: 'Context Strategy', type: 'select', options: ['conservative', 'balanced', 'aggressive'] },
      { key: 'mode', label: 'Mode', type: 'select', options: ['autonomous', 'supervised', 'manual'] },
      { key: 'depth', label: 'Depth', type: 'select', options: ['minimal', 'standard', 'thorough'] },
    ],
  },
  {
    key: 'features',
    title: 'Features',
    sub: 'Feature toggles',
    fields: [
      { key: 'structured_planning', label: 'Structured Planning', type: 'toggle' },
      { key: 'goal_verification', label: 'Goal Verification', type: 'toggle' },
      { key: 'integration_verification', label: 'Integration Verification', type: 'toggle' },
      { key: 'context_isolation', label: 'Context Isolation', type: 'toggle' },
      { key: 'atomic_commits', label: 'Atomic Commits', type: 'toggle' },
      { key: 'session_persistence', label: 'Session Persistence', type: 'toggle' },
      { key: 'research_phase', label: 'Research Phase', type: 'toggle' },
      { key: 'plan_checking', label: 'Plan Checking', type: 'toggle' },
      { key: 'tdd_mode', label: 'TDD Mode', type: 'toggle' },
      { key: 'status_line', label: 'Status Line', type: 'toggle' },
      { key: 'auto_continue', label: 'Auto Continue', type: 'toggle' },
      { key: 'auto_advance', label: 'Auto Advance', type: 'toggle' },
      { key: 'team_discussions', label: 'Team Discussions', type: 'toggle' },
      { key: 'inline_verify', label: 'Inline Verify', type: 'toggle' },
    ],
  },
  {
    key: 'models',
    title: 'Models',
    sub: 'Agent model assignment',
    fields: [
      { key: 'researcher', label: 'Researcher', type: 'select', options: MODEL_OPTIONS },
      { key: 'planner', label: 'Planner', type: 'select', options: MODEL_OPTIONS },
      { key: 'executor', label: 'Executor', type: 'select', options: MODEL_OPTIONS },
      { key: 'verifier', label: 'Verifier', type: 'select', options: MODEL_OPTIONS },
      { key: 'integration_checker', label: 'Integration Checker', type: 'select', options: MODEL_OPTIONS },
      { key: 'debugger', label: 'Debugger', type: 'select', options: MODEL_OPTIONS },
      { key: 'mapper', label: 'Mapper', type: 'select', options: MODEL_OPTIONS },
      { key: 'synthesizer', label: 'Synthesizer', type: 'select', options: MODEL_OPTIONS },
    ],
  },
  {
    key: 'parallelization',
    title: 'Parallelization',
    sub: 'Concurrent execution',
    fields: [
      { key: 'enabled', label: 'Enabled', type: 'toggle' },
      { key: 'plan_level', label: 'Plan Level', type: 'toggle' },
      { key: 'task_level', label: 'Task Level', type: 'toggle' },
      { key: 'max_concurrent_agents', label: 'Max Concurrent Agents', type: 'number', min: 1, max: 10, step: 1 },
      { key: 'min_plans_for_parallel', label: 'Min Plans for Parallel', type: 'number', min: 1, max: 10, step: 1 },
      { key: 'use_teams', label: 'Use Teams', type: 'toggle' },
    ],
  },
  {
    key: 'planning',
    title: 'Planning',
    sub: 'Plan generation',
    fields: [
      { key: 'commit_docs', label: 'Commit Docs', type: 'toggle' },
      { key: 'max_tasks_per_plan', label: 'Max Tasks per Plan', type: 'number', min: 1, max: 10, step: 1 },
      { key: 'search_gitignored', label: 'Search Gitignored', type: 'toggle' },
    ],
  },
  {
    key: 'git',
    title: 'Git',
    sub: 'Version control',
    fields: [
      { key: 'branching', label: 'Branching', type: 'select', options: ['phase', 'feature', 'none'] },
      { key: 'commit_format', label: 'Commit Format', type: 'text' },
      { key: 'phase_branch_template', label: 'Phase Branch Template', type: 'text' },
      { key: 'milestone_branch_template', label: 'Milestone Branch Template', type: 'text' },
      { key: 'mode', label: 'Git Mode', type: 'select', options: ['enabled', 'disabled', 'dry-run'] },
    ],
  },
  {
    key: 'gates',
    title: 'Gates',
    sub: 'Confirmation gates',
    fields: [
      { key: 'confirm_project', label: 'Confirm Project', type: 'toggle' },
      { key: 'confirm_roadmap', label: 'Confirm Roadmap', type: 'toggle' },
      { key: 'confirm_plan', label: 'Confirm Plan', type: 'toggle' },
      { key: 'confirm_execute', label: 'Confirm Execute', type: 'toggle' },
      { key: 'confirm_transition', label: 'Confirm Transition', type: 'toggle' },
      { key: 'issues_review', label: 'Issues Review', type: 'toggle' },
      { key: 'verification', label: 'Verification', type: 'toggle' },
      { key: 'review', label: 'Review', type: 'toggle' },
      { key: 'plan_approval', label: 'Plan Approval', type: 'toggle' },
    ],
  },
  {
    key: 'safety',
    title: 'Safety',
    sub: 'Safety controls',
    fields: [
      { key: 'always_confirm_destructive', label: 'Confirm Destructive', type: 'toggle' },
      { key: 'always_confirm_external_services', label: 'Confirm External Services', type: 'toggle' },
    ],
  },
];

export const QUICK_START_FIELDS = [
  { section: '_root', key: 'mode', label: 'Workflow Mode' },
  { section: '_root', key: 'depth', label: 'Planning Depth' },
  { section: 'features', key: 'tdd_mode', label: 'TDD Mode' },
  { section: 'features', key: 'auto_continue', label: 'Auto Continue' },
  { section: 'parallelization', key: 'enabled', label: 'Parallel Execution' },
  { section: 'planning', key: 'commit_docs', label: 'Commit Planning Docs' },
  { section: 'models', key: 'executor', label: 'Executor Model' },
];
